### ISSUE TITLE
compilation issues due to old jiffy

### ISSUE THREAD

**Issue by tommyjcarpenter** [sinasamavati/leptus#50]
This does not compile using GCC 5.1 or greater due to https://github.com/davisp/jiffy/issues/89, which was resolved in a later version. 

I edited your rebar.config, tried compiling with "branch, master" instead of "tag, 0.8.5", and Leptus compiled. Have not tested extensively yet.

**Comment by sinasamavati** [comment]
Leptus now uses the latest version of Jiffy. So it can be closed.
