### ISSUE TITLE
Update jiffy and msgpack dependencies version

### ISSUE THREAD

**Issue by azhar04** [sinasamavati/leptus#60]
Please update the 'jiffy' and 'msgpack' dependencies version to the latest stable.

**Comment by lk-geimfari** [comment]
@azhar04 Seems like this project is dead. If so, then it's a pity. It was cool project.

**Comment by sinasamavati** [comment]
@azhar04 @lk-geimfari Leptus is back with major changes: 
 the commit 7f6fc82558261b4296a802ecad4267542bd0d554 updates Jiffy, but drops support for msgpack.
