### ISSUE TITLE
leptus is dead?

### ISSUE THREAD

**Issue by ates** [sinasamavati/leptus#61]
Dear Sina,

It's looks like a dead project. There are a lot of issues and most of them without response from you.  I want to know do you plan to  support this project? 
Please confirm the status of this project.

Thanks.

**Comment by silviucpp** [comment]
No commit for 2 years.. what do you think ?

**Comment by ates** [comment]
I know it's dead, just want to have official confirmation from owner.

**Comment by Morsicus** [comment]
So what is a viable alternative ?

**Comment by lukyanov** [comment]
@Morsicus Cowboy 2.0 now seems to include all that leptus offers.

**Comment by sinasamavati** [comment]
I’m probably going to bring this project back to life. I’m afraid I shall ask for donation so that I could do that.

**Comment by sinasamavati** [comment]
Anyone who’s interested in the project, please check out #62.
